import 'dart:convert';
import 'dart:math';

import 'package:crypto/crypto.dart';
import 'package:flutter/material.dart';

/// The icon alphabet used to visualize fingerprints.
/// Icons are picked to have distinct silhouettes and an obvious name,
/// so two fingerprints can be compared out loud and at a glance.
const iconAlphabet = <IconData>[
  Icons.ac_unit,
  Icons.accessibility,
  Icons.agriculture,
  Icons.alarm,
  Icons.album,
  Icons.anchor,
  Icons.android,
  Icons.apartment,
  Icons.apple,
  Icons.architecture,
  Icons.attach_file,
  Icons.attach_money,
  Icons.audiotrack,
  Icons.back_hand,
  Icons.backpack,
  Icons.badge,
  Icons.bakery_dining,
  Icons.balance,
  Icons.bathtub,
  Icons.battery_full,
  Icons.bento,
  Icons.biotech,
  Icons.blender,
  Icons.bluetooth,
  Icons.bolt,
  Icons.bookmark,
  Icons.brush,
  Icons.bug_report,
  Icons.build,
  Icons.cable,
  Icons.cake,
  Icons.calculate,
  Icons.calendar_today,
  Icons.campaign,
  Icons.casino,
  Icons.cast,
  Icons.castle,
  Icons.celebration,
  Icons.cell_tower,
  Icons.chair,
  Icons.change_history,
  Icons.chat,
  Icons.checkroom,
  Icons.church,
  Icons.circle,
  Icons.cloud,
  Icons.coffee_maker,
  Icons.colorize,
  Icons.computer,
  Icons.confirmation_number,
  Icons.content_cut,
  Icons.conveyor_belt,
  Icons.cookie,
  Icons.coronavirus,
  Icons.cottage,
  Icons.credit_card,
  Icons.cruelty_free,
  Icons.cyclone,
  Icons.delete,
  Icons.diamond,
  Icons.directions_bike,
  Icons.directions_boat,
  Icons.directions_bus,
  Icons.directions_car,
  Icons.door_front_door,
  Icons.earbuds,
  Icons.eco,
  Icons.edit,
  Icons.egg,
  Icons.elevator,
  Icons.email,
  Icons.emoji_events,
  Icons.emoji_nature,
  Icons.engineering,
  Icons.explore,
  Icons.extension,
  Icons.face,
  Icons.factory,
  Icons.fastfood,
  Icons.favorite,
  Icons.fence,
  Icons.festival,
  Icons.fingerprint,
  Icons.fire_extinguisher,
  Icons.fireplace,
  Icons.fitness_center,
  Icons.flag,
  Icons.flashlight_on,
  Icons.flight,
  Icons.flutter_dash,
  Icons.forklift,
  Icons.format_paint,
  Icons.gavel,
  Icons.grass,
  Icons.groups,
  Icons.handshake,
  Icons.hardware,
  Icons.headphones,
  Icons.healing,
  Icons.hearing,
  Icons.hexagon,
  Icons.history_edu,
  Icons.hive,
  Icons.home,
  Icons.hourglass_empty,
  Icons.houseboat,
  Icons.hub,
  Icons.ice_skating,
  Icons.icecream,
  Icons.inventory_2,
  Icons.iron,
  Icons.kebab_dining,
  Icons.key,
  Icons.keyboard,
  Icons.king_bed,
  Icons.kitchen,
  Icons.landscape,
  Icons.layers,
  Icons.light,
  Icons.lightbulb,
  Icons.link,
  Icons.liquor,
  Icons.local_bar,
  Icons.local_cafe,
  Icons.local_drink,
  Icons.local_florist,
  Icons.local_gas_station,
  Icons.local_laundry_service,
  Icons.local_mall,
  Icons.local_pizza,
  Icons.local_shipping,
  Icons.local_taxi,
  Icons.location_city,
  Icons.lock,
  Icons.luggage,
  Icons.map,
  Icons.markunread_mailbox,
  Icons.masks,
  Icons.medication,
  Icons.memory,
  Icons.menu,
  Icons.menu_book,
  Icons.mic,
  Icons.microwave,
  Icons.military_tech,
  Icons.monitor_heart,
  Icons.mood,
  Icons.mosque,
  Icons.motorcycle,
  Icons.mouse,
  Icons.movie,
  Icons.museum,
  Icons.newspaper,
  Icons.nightlight,
  Icons.notifications,
  Icons.oil_barrel,
  Icons.outdoor_grill,
  Icons.outlet,
  Icons.palette,
  Icons.park,
  Icons.pentagon,
  Icons.person,
  Icons.pets,
  Icons.phishing,
  Icons.phone,
  Icons.photo_camera,
  Icons.piano,
  Icons.pie_chart,
  Icons.place,
  Icons.pool,
  Icons.power,
  Icons.precision_manufacturing,
  Icons.print,
  Icons.propane_tank,
  Icons.psychology,
  Icons.public,
  Icons.push_pin,
  Icons.qr_code,
  Icons.radar,
  Icons.radio,
  Icons.ramen_dining,
  Icons.receipt,
  Icons.recycling,
  Icons.redeem,
  Icons.refresh,
  Icons.restaurant,
  Icons.rocket,
  Icons.room_service,
  Icons.route,
  Icons.router,
  Icons.sailing,
  Icons.satellite_alt,
  Icons.savings,
  Icons.school,
  Icons.science,
  Icons.search,
  Icons.settings,
  Icons.shelves,
  Icons.shield,
  Icons.shopping_basket,
  Icons.shopping_cart,
  Icons.shower,
  Icons.signpost,
  Icons.sim_card,
  Icons.smart_toy,
  Icons.smartphone,
  Icons.smoking_rooms,
  Icons.soap,
  Icons.solar_power,
  Icons.speaker,
  Icons.sports_esports,
  Icons.sports_football,
  Icons.sports_golf,
  Icons.sports_hockey,
  Icons.sports_motorsports,
  Icons.sports_soccer,
  Icons.sports_tennis,
  Icons.square,
  Icons.stadium,
  Icons.stairs,
  Icons.star,
  Icons.store,
  Icons.straighten,
  Icons.stroller,
  Icons.table_restaurant,
  Icons.tag,
  Icons.temple_buddhist,
  Icons.theater_comedy,
  Icons.theaters,
  Icons.thermostat,
  Icons.thumb_up,
  Icons.toggle_on,
  Icons.toll,
  Icons.tornado,
  Icons.toys,
  Icons.traffic,
  Icons.train,
  Icons.tune,
  Icons.umbrella,
  Icons.usb,
  Icons.vaccines,
  Icons.videocam,
  Icons.view_in_ar,
  Icons.visibility,
  Icons.voicemail,
  Icons.volcano,
  Icons.wallet,
  Icons.warehouse,
  Icons.warning,
  Icons.watch,
  Icons.water_drop,
  Icons.waves,
  Icons.wb_sunny,
  Icons.weekend,
  Icons.whatshot,
  Icons.wifi,
  Icons.wind_power,
  Icons.window,
  Icons.wine_bar,
  Icons.work,
];

/// Hashes the [combined] fingerprints and renders the first 128 bits as 16 icons of [iconAlphabet].
List<IconData> fingerprintToIcons(String combined) {
  final digest = sha256.convert(utf8.encode(combined));
  final hex = digest.bytes.sublist(0, 16).map((b) => b.toRadixString(16).padLeft(2, '0')).join();
  return convertFingerprintToAlphabet(fingerprint: hex, alphabet: iconAlphabet);
}

/// Converts a hex [fingerprint] to a sequence of items of [alphabet] using base conversion.
/// The result has a fixed length depending only on the input and alphabet sizes.
List<T> convertFingerprintToAlphabet<T>({
  required String fingerprint,
  required List<T> alphabet,
}) {
  final base = BigInt.from(alphabet.length);
  final length = (fingerprint.length * 4 * log(2) / log(alphabet.length)).ceil();
  var value = BigInt.parse(fingerprint, radix: 16);
  final result = List<T>.filled(length, alphabet[0]);
  for (var i = length - 1; i >= 0; i--) {
    result[i] = alphabet[(value % base).toInt()];
    value ~/= base;
  }
  return result;
}
