// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.7.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:localsend_app/rust/frb_generated.dart';

Future<void> verifyCert({required String cert, required String publicKey}) =>
    RustLib.instance.api.crateApiCryptoVerifyCert(cert: cert, publicKey: publicKey);
