// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:localsend_app/rust/frb_generated.dart';

/// Lists all non-loopback IPv4 interfaces with their subnet prefix lengths.
/// Returns an empty list rather than an error if the underlying system call
/// fails; callers should treat that as "no mask info available".
Future<List<LocalInterface>> listLocalInterfaces() =>
    RustLib.instance.api.crateApiNetworkListLocalInterfaces();

/// A single non-loopback IPv4 address attached to a local interface, plus the
/// CIDR prefix length of its subnet (e.g. 24 for `/24`, 21 for `/21`).
///
/// Used by the address-input dialog to prefer in-subnet IPs during the wide
/// hashtag scan. Sourced from `getifaddrs(3)` on Unix/Apple/Android and
/// `GetAdaptersAddresses` on Windows via the `if-addrs` crate, so masks are
/// reported for every interface that has an IP — Ethernet, WiFi, VPN, etc.
class LocalInterface {
  final String ip;
  final int prefixLength;

  const LocalInterface({
    required this.ip,
    required this.prefixLength,
  });

  @override
  int get hashCode => ip.hashCode ^ prefixLength.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LocalInterface &&
          runtimeType == other.runtimeType &&
          ip == other.ip &&
          prefixLength == other.prefixLength;
}
