// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:localsend_app/rust/api/stream.dart';
import 'package:localsend_app/rust/frb_generated.dart';

/// Start a QUIC server on the given port with PEM cert/key.
Future<RsQuicServer> quicServerStart({
  required int port,
  required String certPem,
  required String keyPem,
}) => RustLib.instance.api.crateApiQuicQuicServerStart(
  port: port,
  certPem: certPem,
  keyPem: keyPem,
);

/// Accept an incoming connection and perform the Hello handshake.
/// Returns an RsQuicReceiveTransfer handle.
Future<RsQuicReceiveTransfer> quicServerAccept({
  required RsQuicServer server,
}) => RustLib.instance.api.crateApiQuicQuicServerAccept(server: server);

/// Get the local address the QUIC server is bound to.
Future<String> quicServerLocalAddr({required RsQuicServer server}) => RustLib.instance.api.crateApiQuicQuicServerLocalAddr(server: server);

/// Receive the file list from the sender.
/// Returns a JSON-encoded map of file_id -> FileDto.
Future<String> quicReceiveFileList({required RsQuicReceiveTransfer transfer}) =>
    RustLib.instance.api.crateApiQuicQuicReceiveFileList(transfer: transfer);

/// Accept the proposed file list and send tokens back.
Future<void> quicAcceptFiles({
  required RsQuicReceiveTransfer transfer,
  required String sessionId,
  required String fileTokensJson,
}) => RustLib.instance.api.crateApiQuicQuicAcceptFiles(
  transfer: transfer,
  sessionId: sessionId,
  fileTokensJson: fileTokensJson,
);

/// Decline the transfer.
Future<void> quicDecline({required RsQuicReceiveTransfer transfer}) => RustLib.instance.api.crateApiQuicQuicDecline(transfer: transfer);

/// Receive the next file and write it to `output_path`.
///
/// Blocks until the sender opens a new unidirectional stream for the next
/// file. Reads the `FileHeader` (file_id, token), then drains all
/// bytes into the file at `output_path`.
///
/// Returns a JSON object: `{ "fileId": "...", "token": "...", "bytesWritten": 1234 }`.
Future<String> quicReceiveFileToPath({
  required RsQuicReceiveTransfer transfer,
  required String outputPath,
}) => RustLib.instance.api.crateApiQuicQuicReceiveFileToPath(
  transfer: transfer,
  outputPath: outputPath,
);

/// Acknowledge a received file on the control stream.
/// If `error` is `None`, success is reported. Otherwise, the error message is sent.
Future<void> quicAckFile({
  required RsQuicReceiveTransfer transfer,
  required String fileId,
  String? error,
}) => RustLib.instance.api.crateApiQuicQuicAckFile(
  transfer: transfer,
  fileId: fileId,
  error: error,
);

/// Create a new QUIC client.
/// If `server_cert_pem` is provided, only that cert will be trusted.
/// Must be async because Quinn's Endpoint::client requires a Tokio runtime.
Future<RsQuicClient> quicClientNew({String? serverCertPem}) => RustLib.instance.api.crateApiQuicQuicClientNew(serverCertPem: serverCertPem);

/// Connect to a QUIC receiver and perform the Hello handshake.
Future<RsQuicSendTransfer> quicClientConnect({
  required RsQuicClient client,
  required String addr,
  required String alias,
  required String fingerprint,
}) => RustLib.instance.api.crateApiQuicQuicClientConnect(
  client: client,
  addr: addr,
  alias: alias,
  fingerprint: fingerprint,
);

/// Send a file list to the receiver.
/// Returns JSON with { sessionId, files } on accept, or null on decline.
Future<String?> quicPrepareUpload({
  required RsQuicSendTransfer transfer,
  required String filesJson,
}) => RustLib.instance.api.crateApiQuicQuicPrepareUpload(
  transfer: transfer,
  filesJson: filesJson,
);

/// Send a file using memory-mapped I/O (high-performance path).
Future<void> quicSendFileMmap({
  required RsQuicSendTransfer transfer,
  required String filePath,
  required String fileId,
  required String token,
}) => RustLib.instance.api.crateApiQuicQuicSendFileMmap(
  transfer: transfer,
  filePath: filePath,
  fileId: fileId,
  token: token,
);

/// Send a file from a Dart stream (fallback for Android SAF, etc).
Future<void> quicSendFileStream({
  required RsQuicSendTransfer transfer,
  required String fileId,
  required String token,
  required Dart2RustStreamReceiver data,
}) => RustLib.instance.api.crateApiQuicQuicSendFileStream(
  transfer: transfer,
  fileId: fileId,
  token: token,
  data: data,
);

/// Wait for the receiver to acknowledge the last file.
Future<String> quicWaitFileAck({required RsQuicSendTransfer transfer}) => RustLib.instance.api.crateApiQuicQuicWaitFileAck(transfer: transfer);

/// Cancel the transfer.
Future<void> quicCancel({
  required RsQuicSendTransfer transfer,
  required String sessionId,
}) => RustLib.instance.api.crateApiQuicQuicCancel(
  transfer: transfer,
  sessionId: sessionId,
);

/// Signal graceful completion.
Future<void> quicDone({required RsQuicSendTransfer transfer}) => RustLib.instance.api.crateApiQuicQuicDone(transfer: transfer);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<RsQuicClient>>
abstract class RsQuicClient implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<RsQuicReceiveTransfer>>
abstract class RsQuicReceiveTransfer implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<RsQuicSendTransfer>>
abstract class RsQuicSendTransfer implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<RsQuicServer>>
abstract class RsQuicServer implements RustOpaqueInterface {}
