// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:localsend_app/rust/frb_generated.dart';

// These functions are ignored because they are not marked as `pub`: `new`, `open_file_or_uri`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `FileSenderState`, `MmapChunk`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `as_ref`

/// Start a QUIC server on the given port with PEM cert/key.
Future<RsQuicServer> quicServerStart({
  required int port,
  required String certPem,
  required String keyPem,
}) => RustLib.instance.api.crateApiQuicQuicServerStart(
  port: port,
  certPem: certPem,
  keyPem: keyPem,
);

/// Accept an incoming connection and perform the Hello handshake.
/// Returns an RsQuicReceiveTransfer handle and the sender's info as JSON:
/// `{ "version": "3.0", "alias": "...", "fingerprint": "..." }`
Future<(RsQuicReceiveTransfer, String)> quicServerAccept({
  required RsQuicServer server,
  required String serverAlias,
  required String serverFingerprint,
}) => RustLib.instance.api.crateApiQuicQuicServerAccept(
  server: server,
  serverAlias: serverAlias,
  serverFingerprint: serverFingerprint,
);

/// Get the local address the QUIC server is bound to.
Future<String> quicServerLocalAddr({required RsQuicServer server}) => RustLib.instance.api.crateApiQuicQuicServerLocalAddr(server: server);

/// Receive the file list from the sender.
/// Returns a JSON-encoded map of file_id -> FileDto.
Future<String> quicReceiveFileList({required RsQuicReceiveTransfer transfer}) =>
    RustLib.instance.api.crateApiQuicQuicReceiveFileList(transfer: transfer);

/// Accept the proposed file list and send tokens back.
Future<void> quicAcceptFiles({
  required RsQuicReceiveTransfer transfer,
  required String sessionId,
  required String fileTokensJson,
}) => RustLib.instance.api.crateApiQuicQuicAcceptFiles(
  transfer: transfer,
  sessionId: sessionId,
  fileTokensJson: fileTokensJson,
);

/// Decline the transfer.
Future<void> quicDecline({required RsQuicReceiveTransfer transfer}) => RustLib.instance.api.crateApiQuicQuicDecline(transfer: transfer);

/// Acknowledge a received file on the control stream.
/// If `error` is `None`, success is reported. Otherwise, the error message is sent.
Future<void> quicAckFile({
  required RsQuicReceiveTransfer transfer,
  required String fileId,
  String? error,
}) => RustLib.instance.api.crateApiQuicQuicAckFile(
  transfer: transfer,
  fileId: fileId,
  error: error,
);

/// Accepts the next uni stream, reads the file header, then drains all data
/// to disk using Quinn's `read_chunk` (zero-copy from Quinn's recv buffer).
/// Progress is tracked via the atomic counter, polled from Dart via timer.
/// Returns JSON: `{ "fileId": "...", "token": "...", "bytesWritten": 1234, "ackSent": true }`.
Future<String> quicReceiveFileFull({
  required RsQuicReceiveTransfer transfer,
  required String outputPath,
}) => RustLib.instance.api.crateApiQuicQuicReceiveFileFull(
  transfer: transfer,
  outputPath: outputPath,
);

/// Create a new QUIC client.
/// If `server_cert_pem` is provided, only that cert will be trusted.
/// Must be async because Quinn's Endpoint::client requires a Tokio runtime.
Future<RsQuicClient> quicClientNew({String? serverCertPem}) => RustLib.instance.api.crateApiQuicQuicClientNew(serverCertPem: serverCertPem);

/// Connect to a QUIC receiver and perform the Hello handshake.
Future<RsQuicSendTransfer> quicClientConnect({
  required RsQuicClient client,
  required String addr,
  required String alias,
  required String fingerprint,
}) => RustLib.instance.api.crateApiQuicQuicClientConnect(
  client: client,
  addr: addr,
  alias: alias,
  fingerprint: fingerprint,
);

/// Send a file list to the receiver.
/// Returns JSON with { sessionId, files } on accept, or null on decline.
Future<String?> quicPrepareUpload({
  required RsQuicSendTransfer transfer,
  required String filesJson,
}) => RustLib.instance.api.crateApiQuicQuicPrepareUpload(
  transfer: transfer,
  filesJson: filesJson,
);

/// Send a file using memory-mapped I/O in a **single** FFI call.
///
/// Handles both regular file paths and Android `content://` URIs.
/// On Android, SAF content URIs are resolved via JNI
/// (`ContentResolver.openFileDescriptor`) to a raw fd, then mmap'd.
Future<void> quicSendFileMmap({
  required RsQuicSendTransfer transfer,
  required String filePath,
  required String fileId,
  required String token,
}) => RustLib.instance.api.crateApiQuicQuicSendFileMmap(
  transfer: transfer,
  filePath: filePath,
  fileId: fileId,
  token: token,
);

/// Step 1 (stream): Open uni stream, send header.
/// Dart will push chunks via `quic_send_file_write_chunk`.
Future<void> quicSendFileStart({
  required RsQuicSendTransfer transfer,
  required String fileId,
  required String token,
}) => RustLib.instance.api.crateApiQuicQuicSendFileStart(
  transfer: transfer,
  fileId: fileId,
  token: token,
);

/// Step 2 (stream): Write a chunk of data from Dart to the QUIC stream.
Future<void> quicSendFileWriteChunk({
  required RsQuicSendTransfer transfer,
  required List<int> data,
}) => RustLib.instance.api.crateApiQuicQuicSendFileWriteChunk(
  transfer: transfer,
  data: data,
);

/// Step 3 (both): Finish the uni stream (send FIN).
Future<void> quicSendFileFinish({required RsQuicSendTransfer transfer}) => RustLib.instance.api.crateApiQuicQuicSendFileFinish(transfer: transfer);

/// Cancel the transfer.
Future<void> quicCancel({
  required RsQuicSendTransfer transfer,
  required String sessionId,
}) => RustLib.instance.api.crateApiQuicQuicCancel(
  transfer: transfer,
  sessionId: sessionId,
);

/// Signal graceful completion.
Future<void> quicDone({required RsQuicSendTransfer transfer}) => RustLib.instance.api.crateApiQuicQuicDone(transfer: transfer);

/// Get the total number of bytes sent so far across all files.
/// This reads an atomic counter — no mutex lock needed.
Future<BigInt> quicGetSendProgress({required RsQuicSendTransfer transfer}) =>
    RustLib.instance.api.crateApiQuicQuicGetSendProgress(transfer: transfer);

/// Get the total number of bytes received so far across all files.
/// This reads an atomic counter — no mutex lock needed.
Future<BigInt> quicGetReceiveProgress({
  required RsQuicReceiveTransfer transfer,
}) => RustLib.instance.api.crateApiQuicQuicGetReceiveProgress(transfer: transfer);

/// Get per-file send progress for a parallel transfer.
/// Returns JSON: `{ "fileId1": 1234, "fileId2": 5678 }`
Future<String> quicGetParallelSendProgress({
  required RsQuicSendTransfer transfer,
}) => RustLib.instance.api.crateApiQuicQuicGetParallelSendProgress(
  transfer: transfer,
);

/// Get per-file receive progress for a parallel transfer.
/// Returns JSON: `{ "fileId1": 1234, "fileId2": 5678 }`
Future<String> quicGetParallelReceiveProgress({
  required RsQuicReceiveTransfer transfer,
}) => RustLib.instance.api.crateApiQuicQuicGetParallelReceiveProgress(
  transfer: transfer,
);

/// Send multiple files in parallel over independent QUIC uni streams.
///
/// Each file gets its own uni stream; Quinn multiplexes them at the
/// transport level (no head-of-line blocking between files).
///
/// `files_json`: `[{"filePath":"…","fileId":"…","token":"…"}, …]`
///
/// For single files, prefer `quic_send_file_mmap` — no task overhead.
Future<void> quicSendFilesParallel({
  required RsQuicSendTransfer transfer,
  required String filesJson,
}) => RustLib.instance.api.crateApiQuicQuicSendFilesParallel(
  transfer: transfer,
  filesJson: filesJson,
);

/// Receive multiple files in parallel from independent QUIC uni streams.
///
/// Spawns one Tokio task per expected file. Each task accepts the next
/// available uni stream, reads the `FileHeader`, and writes data to the
/// corresponding output path. ACKs are sent after all tasks complete.
///
/// `files_json`: `[{"fileId":"…","outputPath":"…"}, …]`
///
/// Returns JSON: `{ "succeeded": ["id1", "id2"], "failed": ["id3"] }`
///
/// For single files, prefer `quic_receive_file_start/read_chunk/finish`.
Future<String> quicReceiveFilesParallel({
  required RsQuicReceiveTransfer transfer,
  required String filesJson,
}) => RustLib.instance.api.crateApiQuicQuicReceiveFilesParallel(
  transfer: transfer,
  filesJson: filesJson,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<RsQuicClient>>
abstract class RsQuicClient implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<RsQuicReceiveTransfer>>
abstract class RsQuicReceiveTransfer implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<RsQuicSendTransfer>>
abstract class RsQuicSendTransfer implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<RsQuicServer>>
abstract class RsQuicServer implements RustOpaqueInterface {}
