// Mocks generated by Mockito 5.4.6 from annotations
// in localsend_app/test/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:common/model/device.dart' as _i13;
import 'package:common/model/stored_security_context.dart' as _i2;
import 'package:flutter/material.dart' as _i9;
import 'package:localsend_app/gen/strings.g.dart' as _i11;
import 'package:localsend_app/model/persistence/color_mode.dart' as _i10;
import 'package:localsend_app/model/persistence/favorite_device.dart' as _i7;
import 'package:localsend_app/model/persistence/receive_history_entry.dart' as _i6;
import 'package:localsend_app/model/send_mode.dart' as _i12;
import 'package:localsend_app/provider/persistence_provider.dart' as _i4;
import 'package:localsend_app/rust/api/model.dart' as _i16;
import 'package:localsend_app/rust/api/webrtc.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:shared_preferences/shared_preferences.dart' as _i14;
import 'package:uuid/uuid.dart' as _i15;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeStoredSecurityContext_0 extends _i1.SmartFake implements _i2.StoredSecurityContext {
  _FakeStoredSecurityContext_0(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

class _FakeRtcReceiveController_1 extends _i1.SmartFake implements _i3.RtcReceiveController {
  _FakeRtcReceiveController_1(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

class _FakeRtcSendController_2 extends _i1.SmartFake implements _i3.RtcSendController {
  _FakeRtcSendController_2(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

/// A class which mocks [PersistenceService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPersistenceService extends _i1.Mock implements _i4.PersistenceService {
  @override
  bool get isFirstAppStart =>
      (super.noSuchMethod(
            Invocation.getter(#isFirstAppStart),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool isPortableMode() =>
      (super.noSuchMethod(
            Invocation.method(#isPortableMode, []),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i2.StoredSecurityContext getSecurityContext() =>
      (super.noSuchMethod(
            Invocation.method(#getSecurityContext, []),
            returnValue: _FakeStoredSecurityContext_0(
              this,
              Invocation.method(#getSecurityContext, []),
            ),
            returnValueForMissingStub: _FakeStoredSecurityContext_0(
              this,
              Invocation.method(#getSecurityContext, []),
            ),
          )
          as _i2.StoredSecurityContext);

  @override
  _i5.Future<void> setSecurityContext(_i2.StoredSecurityContext? context) =>
      (super.noSuchMethod(
            Invocation.method(#setSecurityContext, [context]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> setSignalingServers(List<String>? servers) =>
      (super.noSuchMethod(
            Invocation.method(#setSignalingServers, [servers]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> setStunServers(List<String>? servers) =>
      (super.noSuchMethod(
            Invocation.method(#setStunServers, [servers]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  List<_i6.ReceiveHistoryEntry> getReceiveHistory() =>
      (super.noSuchMethod(
            Invocation.method(#getReceiveHistory, []),
            returnValue: <_i6.ReceiveHistoryEntry>[],
            returnValueForMissingStub: <_i6.ReceiveHistoryEntry>[],
          )
          as List<_i6.ReceiveHistoryEntry>);

  @override
  _i5.Future<void> setReceiveHistory(List<_i6.ReceiveHistoryEntry>? entries) =>
      (super.noSuchMethod(
            Invocation.method(#setReceiveHistory, [entries]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  List<_i7.FavoriteDevice> getFavorites() =>
      (super.noSuchMethod(
            Invocation.method(#getFavorites, []),
            returnValue: <_i7.FavoriteDevice>[],
            returnValueForMissingStub: <_i7.FavoriteDevice>[],
          )
          as List<_i7.FavoriteDevice>);

  @override
  _i5.Future<void> setFavorites(List<_i7.FavoriteDevice>? entries) =>
      (super.noSuchMethod(
            Invocation.method(#setFavorites, [entries]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  String getShowToken() =>
      (super.noSuchMethod(
            Invocation.method(#getShowToken, []),
            returnValue: _i8.dummyValue<String>(
              this,
              Invocation.method(#getShowToken, []),
            ),
            returnValueForMissingStub: _i8.dummyValue<String>(
              this,
              Invocation.method(#getShowToken, []),
            ),
          )
          as String);

  @override
  String getAlias() =>
      (super.noSuchMethod(
            Invocation.method(#getAlias, []),
            returnValue: _i8.dummyValue<String>(
              this,
              Invocation.method(#getAlias, []),
            ),
            returnValueForMissingStub: _i8.dummyValue<String>(
              this,
              Invocation.method(#getAlias, []),
            ),
          )
          as String);

  @override
  _i5.Future<void> setAlias(String? alias) =>
      (super.noSuchMethod(
            Invocation.method(#setAlias, [alias]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i9.ThemeMode getTheme() =>
      (super.noSuchMethod(
            Invocation.method(#getTheme, []),
            returnValue: _i9.ThemeMode.system,
            returnValueForMissingStub: _i9.ThemeMode.system,
          )
          as _i9.ThemeMode);

  @override
  _i5.Future<void> setTheme(_i9.ThemeMode? theme) =>
      (super.noSuchMethod(
            Invocation.method(#setTheme, [theme]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i10.ColorMode getColorMode() =>
      (super.noSuchMethod(
            Invocation.method(#getColorMode, []),
            returnValue: _i10.ColorMode.system,
            returnValueForMissingStub: _i10.ColorMode.system,
          )
          as _i10.ColorMode);

  @override
  _i5.Future<void> setColorMode(_i10.ColorMode? color) =>
      (super.noSuchMethod(
            Invocation.method(#setColorMode, [color]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> setLocale(_i11.AppLocale? locale) =>
      (super.noSuchMethod(
            Invocation.method(#setLocale, [locale]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  int getPort() =>
      (super.noSuchMethod(
            Invocation.method(#getPort, []),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  _i5.Future<void> setPort(int? port) =>
      (super.noSuchMethod(
            Invocation.method(#setPort, [port]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> setNetworkWhitelist(List<String>? whitelist) =>
      (super.noSuchMethod(
            Invocation.method(#setNetworkWhitelist, [whitelist]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> setNetworkBlacklist(List<String>? blacklist) =>
      (super.noSuchMethod(
            Invocation.method(#setNetworkBlacklist, [blacklist]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  int getDiscoveryTimeout() =>
      (super.noSuchMethod(
            Invocation.method(#getDiscoveryTimeout, []),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  _i5.Future<void> setDiscoveryTimeout(int? timeout) =>
      (super.noSuchMethod(
            Invocation.method(#setDiscoveryTimeout, [timeout]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  bool getShareViaLinkAutoAccept() =>
      (super.noSuchMethod(
            Invocation.method(#getShareViaLinkAutoAccept, []),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i5.Future<void> setShareViaLinkAutoAccept(bool? shareViaLinkAutoAccept) =>
      (super.noSuchMethod(
            Invocation.method(#setShareViaLinkAutoAccept, [
              shareViaLinkAutoAccept,
            ]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  String getMulticastGroup() =>
      (super.noSuchMethod(
            Invocation.method(#getMulticastGroup, []),
            returnValue: _i8.dummyValue<String>(
              this,
              Invocation.method(#getMulticastGroup, []),
            ),
            returnValueForMissingStub: _i8.dummyValue<String>(
              this,
              Invocation.method(#getMulticastGroup, []),
            ),
          )
          as String);

  @override
  _i5.Future<void> setMulticastGroup(String? group) =>
      (super.noSuchMethod(
            Invocation.method(#setMulticastGroup, [group]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> setDestination(String? destination) =>
      (super.noSuchMethod(
            Invocation.method(#setDestination, [destination]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  bool isSaveToGallery() =>
      (super.noSuchMethod(
            Invocation.method(#isSaveToGallery, []),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i5.Future<void> setSaveToGallery(bool? saveToGallery) =>
      (super.noSuchMethod(
            Invocation.method(#setSaveToGallery, [saveToGallery]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  bool isSaveToHistory() =>
      (super.noSuchMethod(
            Invocation.method(#isSaveToHistory, []),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i5.Future<void> setSaveToHistory(bool? saveToHistory) =>
      (super.noSuchMethod(
            Invocation.method(#setSaveToHistory, [saveToHistory]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  bool getAdvancedSettingsEnabled() =>
      (super.noSuchMethod(
            Invocation.method(#getAdvancedSettingsEnabled, []),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i5.Future<void> setAdvancedSettingsEnabled(bool? isEnabled) =>
      (super.noSuchMethod(
            Invocation.method(#setAdvancedSettingsEnabled, [isEnabled]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  bool isQuickSave() =>
      (super.noSuchMethod(
            Invocation.method(#isQuickSave, []),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i5.Future<void> setQuickSave(bool? quickSave) =>
      (super.noSuchMethod(
            Invocation.method(#setQuickSave, [quickSave]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  bool isQuickSaveFromFavorites() =>
      (super.noSuchMethod(
            Invocation.method(#isQuickSaveFromFavorites, []),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i5.Future<void> setQuickSaveFromFavorites(bool? quickSaveFromFavorites) =>
      (super.noSuchMethod(
            Invocation.method(#setQuickSaveFromFavorites, [
              quickSaveFromFavorites,
            ]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> setReceivePin(String? pin) =>
      (super.noSuchMethod(
            Invocation.method(#setReceivePin, [pin]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  bool isAutoFinish() =>
      (super.noSuchMethod(
            Invocation.method(#isAutoFinish, []),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i5.Future<void> setAutoFinish(bool? autoFinish) =>
      (super.noSuchMethod(
            Invocation.method(#setAutoFinish, [autoFinish]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  bool isMinimizeToTray() =>
      (super.noSuchMethod(
            Invocation.method(#isMinimizeToTray, []),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i5.Future<void> setMinimizeToTray(bool? minimizeToTray) =>
      (super.noSuchMethod(
            Invocation.method(#setMinimizeToTray, [minimizeToTray]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  bool isHttps() =>
      (super.noSuchMethod(
            Invocation.method(#isHttps, []),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i5.Future<void> setHttps(bool? https) =>
      (super.noSuchMethod(
            Invocation.method(#setHttps, [https]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i12.SendMode getSendMode() =>
      (super.noSuchMethod(
            Invocation.method(#getSendMode, []),
            returnValue: _i12.SendMode.single,
            returnValueForMissingStub: _i12.SendMode.single,
          )
          as _i12.SendMode);

  @override
  _i5.Future<void> setSendMode(_i12.SendMode? mode) =>
      (super.noSuchMethod(
            Invocation.method(#setSendMode, [mode]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> setWindowOffsetX(double? x) =>
      (super.noSuchMethod(
            Invocation.method(#setWindowOffsetX, [x]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> setWindowOffsetY(double? y) =>
      (super.noSuchMethod(
            Invocation.method(#setWindowOffsetY, [y]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> setWindowHeight(double? height) =>
      (super.noSuchMethod(
            Invocation.method(#setWindowHeight, [height]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> setWindowWidth(double? width) =>
      (super.noSuchMethod(
            Invocation.method(#setWindowWidth, [width]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> setSaveWindowPlacement(bool? savePlacement) =>
      (super.noSuchMethod(
            Invocation.method(#setSaveWindowPlacement, [savePlacement]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  bool getSaveWindowPlacement() =>
      (super.noSuchMethod(
            Invocation.method(#getSaveWindowPlacement, []),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i5.Future<void> setEnableAnimations(bool? enableAnimations) =>
      (super.noSuchMethod(
            Invocation.method(#setEnableAnimations, [enableAnimations]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  bool getEnableAnimations() =>
      (super.noSuchMethod(
            Invocation.method(#getEnableAnimations, []),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i5.Future<void> setDeviceType(_i13.DeviceType? deviceType) =>
      (super.noSuchMethod(
            Invocation.method(#setDeviceType, [deviceType]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> setDeviceModel(String? deviceModel) =>
      (super.noSuchMethod(
            Invocation.method(#setDeviceModel, [deviceModel]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> clear() =>
      (super.noSuchMethod(
            Invocation.method(#clear, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [SharedPreferences].
///
/// See the documentation for Mockito's code generation for more information.
class MockSharedPreferences extends _i1.Mock implements _i14.SharedPreferences {
  @override
  Set<String> getKeys() =>
      (super.noSuchMethod(
            Invocation.method(#getKeys, []),
            returnValue: <String>{},
            returnValueForMissingStub: <String>{},
          )
          as Set<String>);

  @override
  Object? get(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#get, [key]),
            returnValueForMissingStub: null,
          )
          as Object?);

  @override
  bool? getBool(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#getBool, [key]),
            returnValueForMissingStub: null,
          )
          as bool?);

  @override
  int? getInt(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#getInt, [key]),
            returnValueForMissingStub: null,
          )
          as int?);

  @override
  double? getDouble(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#getDouble, [key]),
            returnValueForMissingStub: null,
          )
          as double?);

  @override
  String? getString(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#getString, [key]),
            returnValueForMissingStub: null,
          )
          as String?);

  @override
  bool containsKey(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#containsKey, [key]),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  List<String>? getStringList(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#getStringList, [key]),
            returnValueForMissingStub: null,
          )
          as List<String>?);

  @override
  _i5.Future<bool> setBool(String? key, bool? value) =>
      (super.noSuchMethod(
            Invocation.method(#setBool, [key, value]),
            returnValue: _i5.Future<bool>.value(false),
            returnValueForMissingStub: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> setInt(String? key, int? value) =>
      (super.noSuchMethod(
            Invocation.method(#setInt, [key, value]),
            returnValue: _i5.Future<bool>.value(false),
            returnValueForMissingStub: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> setDouble(String? key, double? value) =>
      (super.noSuchMethod(
            Invocation.method(#setDouble, [key, value]),
            returnValue: _i5.Future<bool>.value(false),
            returnValueForMissingStub: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> setString(String? key, String? value) =>
      (super.noSuchMethod(
            Invocation.method(#setString, [key, value]),
            returnValue: _i5.Future<bool>.value(false),
            returnValueForMissingStub: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> setStringList(String? key, List<String>? value) =>
      (super.noSuchMethod(
            Invocation.method(#setStringList, [key, value]),
            returnValue: _i5.Future<bool>.value(false),
            returnValueForMissingStub: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> remove(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#remove, [key]),
            returnValue: _i5.Future<bool>.value(false),
            returnValueForMissingStub: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> commit() =>
      (super.noSuchMethod(
            Invocation.method(#commit, []),
            returnValue: _i5.Future<bool>.value(false),
            returnValueForMissingStub: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> clear() =>
      (super.noSuchMethod(
            Invocation.method(#clear, []),
            returnValue: _i5.Future<bool>.value(false),
            returnValueForMissingStub: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<void> reload() =>
      (super.noSuchMethod(
            Invocation.method(#reload, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [LsSignalingConnection].
///
/// See the documentation for Mockito's code generation for more information.
class MockLsSignalingConnection extends _i1.Mock implements _i3.LsSignalingConnection {
  @override
  bool get isDisposed =>
      (super.noSuchMethod(
            Invocation.getter(#isDisposed),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i5.Future<_i3.RtcReceiveController> acceptOffer({
    required List<String>? stunServers,
    required _i3.WsServerSdpMessage? offer,
    required String? privateKey,
    _i3.ExpectingPublicKey? expectingPublicKey,
    _i3.PinConfig? pin,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#acceptOffer, [], {
              #stunServers: stunServers,
              #offer: offer,
              #privateKey: privateKey,
              #expectingPublicKey: expectingPublicKey,
              #pin: pin,
            }),
            returnValue: _i5.Future<_i3.RtcReceiveController>.value(
              _FakeRtcReceiveController_1(
                this,
                Invocation.method(#acceptOffer, [], {
                  #stunServers: stunServers,
                  #offer: offer,
                  #privateKey: privateKey,
                  #expectingPublicKey: expectingPublicKey,
                  #pin: pin,
                }),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i3.RtcReceiveController>.value(
              _FakeRtcReceiveController_1(
                this,
                Invocation.method(#acceptOffer, [], {
                  #stunServers: stunServers,
                  #offer: offer,
                  #privateKey: privateKey,
                  #expectingPublicKey: expectingPublicKey,
                  #pin: pin,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.RtcReceiveController>);

  @override
  _i5.Future<_i3.RtcSendController> sendOffer({
    required List<String>? stunServers,
    required _i15.UuidValue? target,
    required String? privateKey,
    _i3.ExpectingPublicKey? expectingPublicKey,
    _i3.PinConfig? pin,
    required List<_i16.FileDto>? files,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendOffer, [], {
              #stunServers: stunServers,
              #target: target,
              #privateKey: privateKey,
              #expectingPublicKey: expectingPublicKey,
              #pin: pin,
              #files: files,
            }),
            returnValue: _i5.Future<_i3.RtcSendController>.value(
              _FakeRtcSendController_2(
                this,
                Invocation.method(#sendOffer, [], {
                  #stunServers: stunServers,
                  #target: target,
                  #privateKey: privateKey,
                  #expectingPublicKey: expectingPublicKey,
                  #pin: pin,
                  #files: files,
                }),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i3.RtcSendController>.value(
              _FakeRtcSendController_2(
                this,
                Invocation.method(#sendOffer, [], {
                  #stunServers: stunServers,
                  #target: target,
                  #privateKey: privateKey,
                  #expectingPublicKey: expectingPublicKey,
                  #pin: pin,
                  #files: files,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.RtcSendController>);

  @override
  _i5.Future<void> updateInfo({required _i3.ProposingClientInfo? info}) =>
      (super.noSuchMethod(
            Invocation.method(#updateInfo, [], {#info: info}),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}
