// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:localsend_isolates/rust/api/model.dart';
import 'package:localsend_isolates/rust/frb_generated.dart';

/// Reads the timestamps of the file at `path` in the protocol's RFC 3339
/// format with nanosecond precision, which Dart's `DateTime` cannot express.
/// `None` when the file cannot be inspected or provides no timestamps.
Future<FileMetadata?> readFileMetadata({required String path}) => RustLib.instance.api.crateApiMetadataReadFileMetadata(path: path);
