// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:localsend_isolates/rust/api/model.dart';
import 'package:localsend_isolates/rust/api/server.dart';
import 'package:localsend_isolates/rust/frb_generated.dart';

/// Starts UDP multicast discovery: binds the multicast sockets on all usable
/// network interfaces and listens for announcements of other devices.
///
/// Announcements are sent to the IPv4 [group] and, as a LocalSend extension,
/// to the (currently hardcoded) IPv6 group `ff12::fd3a:e420`.
///
/// [port] is used both to bind the multicast sockets and as the HTTP server
/// port announced to other devices.
///
/// Nothing is announced until [RsMulticast::announce] is called.
///
/// Fails when [group] is not a valid IPv4 address or when no network
/// interface could be used at all.
Future<RsMulticast> startMulticast({
  required String group,
  required int port,
  List<String>? networkWhitelist,
  List<String>? networkBlacklist,
  required String alias,
  required String version,
  String? deviceModel,
  DeviceType? deviceType,
  required String fingerprint,
  required ProtocolTypeV2 protocol,
  required bool download,
}) => RustLib.instance.api.crateApiMulticastStartMulticast(
  group: group,
  port: port,
  networkWhitelist: networkWhitelist,
  networkBlacklist: networkBlacklist,
  alias: alias,
  version: version,
  deviceModel: deviceModel,
  deviceType: deviceType,
  fingerprint: fingerprint,
  protocol: protocol,
  download: download,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<RsMulticast>>
abstract class RsMulticast implements RustOpaqueInterface {
  /// Announces this device to the network, which makes every other LocalSend
  /// device on it register with this device over HTTP.
  ///
  /// Returns once the whole announcement burst has been sent, which takes a
  /// few seconds, or immediately once discovery has been stopped.
  Future<void> announce();

  /// Emits a [RsMulticastDiscovered] for every announcement received from
  /// another device until discovery is stopped.
  /// Can only be listened to once.
  Stream<RsMulticastDiscovered> listen();

  /// Stops discovery, which also ends the [RsMulticast::listen] stream.
  /// Returns after all sockets are closed, so the port can be bound again.
  Future<void> stop();
}

class MulticastMessageV2 {
  final String alias;
  final String version;
  final String? deviceModel;
  final DeviceType? deviceType;
  final String fingerprint;
  final int port;
  final ProtocolTypeV2 protocol;
  final bool download;

  const MulticastMessageV2({
    required this.alias,
    required this.version,
    this.deviceModel,
    this.deviceType,
    required this.fingerprint,
    required this.port,
    required this.protocol,
    required this.download,
  });

  @override
  int get hashCode =>
      alias.hashCode ^
      version.hashCode ^
      deviceModel.hashCode ^
      deviceType.hashCode ^
      fingerprint.hashCode ^
      port.hashCode ^
      protocol.hashCode ^
      download.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MulticastMessageV2 &&
          runtimeType == other.runtimeType &&
          alias == other.alias &&
          version == other.version &&
          deviceModel == other.deviceModel &&
          deviceType == other.deviceType &&
          fingerprint == other.fingerprint &&
          port == other.port &&
          protocol == other.protocol &&
          download == other.download;
}

/// Another device announced itself via UDP multicast.
///
/// The peer expects to be answered with an HTTP register request.
class RsMulticastDiscovered {
  /// The address the announcement was sent from. The peer's HTTP server is
  /// reachable at this address on `message.port`.
  ///
  /// A link-local IPv6 source carries its interface scope as `fe80::1%3`,
  /// which the Rust HTTP client accepts back as a host.
  final String ip;

  /// The announcement as it was received.
  final MulticastMessageV2 message;

  const RsMulticastDiscovered({
    required this.ip,
    required this.message,
  });

  @override
  int get hashCode => ip.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) || other is RsMulticastDiscovered && runtimeType == other.runtimeType && ip == other.ip && message == other.message;
}
