name: Publish to WinGet
on:
  release:
    types: [released]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Publish LocalSend
        uses: vedantmgoyal9/winget-releaser@main
        with:
          identifier: LocalSend.LocalSend
          installers-regex: 'LocalSend-(?!CLI-).*\.exe$'
          token: ${{ secrets.WINGET_TOKEN }}
      - name: Publish LocalSend CLI
        uses: vedantmgoyal9/winget-releaser@main
        with:
          identifier: LocalSend.LocalSend.CLI
          installers-regex: 'LocalSend-CLI-.*\.exe$'
          token: ${{ secrets.WINGET_TOKEN }}
