name: Publish to WinGet
on:
  release:
    types: [released]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: vedantmgoyal9/winget-releaser@7bd472be23763def6e16bd06cc8b1cdfab0e2fd5 # main
        with:
          identifier: LocalSend.LocalSend
          token: ${{ secrets.WINGET_TOKEN }}
